#!/usr/bin/env python3

# ─────────────────────────────────────────────────────────────────────────────
# send-test-email.py
#
# Sends a test email with a .ics attachment from Gmail to the Proton address
# configured in config.env. Used to test the goimapnotify -> ics-sync.py
# trigger path without needing a real calendar invitation.
#
# The email lands in the Proton inbox. Move it manually to the watched
# folder (Folders/Static/BouncePickle) and check if goimapnotify fires.
#
# Requires GMAIL_USER and GMAIL_APP_PASS in config.env.
# Generate an app password at https://myaccount.google.com/apppasswords
# ─────────────────────────────────────────────────────────────────────────────

import sys
import smtplib
import datetime
import uuid
from pathlib import Path
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

# ─────────────────────────────────────────────────────────────────────────────
# LOAD CONFIG
# ─────────────────────────────────────────────────────────────────────────────
SCRIPT_DIR = Path(__file__).parent.resolve()
CONFIG_FILE = SCRIPT_DIR / "config.env"

if not CONFIG_FILE.exists():
    print(f"ERROR: config.env not found at {CONFIG_FILE}")
    sys.exit(1)

config = {}
with open(CONFIG_FILE) as f:
    for line in f:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, raw_value = line.partition("=")
        key = key.strip()
        value = raw_value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
            value = value[1:-1]
        config[key] = value

required = ["PROTON_EMAIL", "GMAIL_USER", "GMAIL_APP_PASS"]
missing = [k for k in required if not config.get(k)]
if missing:
    print(f"ERROR: Missing required config values: {', '.join(missing)}")
    print("Add GMAIL_USER and GMAIL_APP_PASS to config.env.")
    print("Generate an app password at https://myaccount.google.com/apppasswords")
    sys.exit(1)

PROTON_EMAIL = config["PROTON_EMAIL"]
GMAIL_USER = config["GMAIL_USER"]
GMAIL_APP_PASS = config["GMAIL_APP_PASS"]

# ─────────────────────────────────────────────────────────────────────────────
# GENERATE TEST .ICS
# Creates a VEVENT one hour from now so it shows up as upcoming.
# ─────────────────────────────────────────────────────────────────────────────
def generate_test_ics():
    now = datetime.datetime.utcnow()
    start = now + datetime.timedelta(hours=1)
    end = start + datetime.timedelta(hours=1)
    uid = f"test-{uuid.uuid4()}"
    timestamp = now.strftime("%Y%m%dT%H%M%SZ")

    ics = (
        "BEGIN:VCALENDAR\r\n"
        "VERSION:2.0\r\n"
        "PRODID:-//ics-sync test//EN\r\n"
        "BEGIN:VEVENT\r\n"
        f"UID:{uid}\r\n"
        f"DTSTAMP:{timestamp}\r\n"
        f"DTSTART:{start.strftime('%Y%m%dT%H%M%SZ')}\r\n"
        f"DTEND:{end.strftime('%Y%m%dT%H%M%SZ')}\r\n"
        f"SUMMARY:Auto-sync test {now.strftime('%Y-%m-%d %H:%M')}\r\n"
        "DESCRIPTION:Test event generated by send-test-email.py\r\n"
        "END:VEVENT\r\n"
        "END:VCALENDAR\r\n"
    )
    return uid, ics

# ─────────────────────────────────────────────────────────────────────────────
# SEND
# ─────────────────────────────────────────────────────────────────────────────
def main():
    uid, ics_data = generate_test_ics()

    msg = MIMEMultipart()
    msg["From"] = GMAIL_USER
    msg["To"] = PROTON_EMAIL
    msg["Subject"] = f"ics-sync test {datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M')}"

    body = "This is an automated test email from send-test-email.py with a .ics attachment."
    msg.attach(MIMEText(body, "plain"))

    attachment = MIMEBase("text", "calendar", name="test-event.ics")
    attachment.set_payload(ics_data.encode("utf-8"))
    encoders.encode_base64(attachment)
    attachment.add_header("Content-Disposition", "attachment", filename="test-event.ics")
    msg.attach(attachment)

    print(f"Sending test email to {PROTON_EMAIL} from {GMAIL_USER}...")
    print(f"Event UID: {uid}")

    try:
        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.starttls()
            server.login(GMAIL_USER, GMAIL_APP_PASS)
            server.sendmail(GMAIL_USER, PROTON_EMAIL, msg.as_string())
        print("Sent successfully.")
        print()
        print("Next steps:")
        print("  1. Wait for the email to arrive in Proton Mail")
        print("  2. Move it to Folders/Static/BouncePickle")
        print("  3. Check: journalctl --user -u goimapnotify --since '5 minutes ago'")
        print(f"  4. Verify event in Radicale with UID: {uid}")
    except smtplib.SMTPAuthenticationError:
        print("ERROR: Gmail authentication failed.")
        print("Check GMAIL_USER and GMAIL_APP_PASS in config.env.")
        print("Make sure you are using an app password, not your regular password.")
        print("Generate one at https://myaccount.google.com/apppasswords")
        sys.exit(1)
    except Exception as e:
        print(f"ERROR: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
